include:
- board: nrfmicro_13
  shield: cornix_L
  snippet: studio-rpc-usb-uart
#  snippet: nrf52840-nosd
- board: nrfmicro_13
  shield: cornix_R
#  snippet：nrf52840-nosd
- board: nrfmicro_13
  shield: settings_reset
